/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicLayoutImport } from './routes/_publicLayout'
import { Route as ProtectedLayoutImport } from './routes/_protectedLayout'
import { Route as ProtectedLayoutIndexImport } from './routes/_protectedLayout/index'
import { Route as ProtectedLayoutTransactionsLayoutImport } from './routes/_protectedLayout/_transactionsLayout'
import { Route as PublicLayoutLoginIndexImport } from './routes/_publicLayout/login/index'
import { Route as ProtectedLayoutPayeesIndexImport } from './routes/_protectedLayout/payees/index'
import { Route as ProtectedLayoutAccountsIndexImport } from './routes/_protectedLayout/accounts/index'
import { Route as ProtectedLayoutTransactionsLayoutTransactionsListIndexImport } from './routes/_protectedLayout/_transactionsLayout/transactions/list/index'
import { Route as ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexImport } from './routes/_protectedLayout/_transactionsLayout/transactions/spendings/payees/index'
import { Route as ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexImport } from './routes/_protectedLayout/_transactionsLayout/transactions/spendings/categories/index'

// Create/Update Routes

const PublicLayoutRoute = PublicLayoutImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_protectedLayout',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutIndexRoute = ProtectedLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedLayoutTransactionsLayoutRoute =
  ProtectedLayoutTransactionsLayoutImport.update({
    id: '/_transactionsLayout',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const PublicLayoutLoginIndexRoute = PublicLayoutLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const ProtectedLayoutPayeesIndexRoute = ProtectedLayoutPayeesIndexImport.update(
  {
    id: '/payees/',
    path: '/payees/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any,
)

const ProtectedLayoutAccountsIndexRoute =
  ProtectedLayoutAccountsIndexImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedLayoutTransactionsLayoutTransactionsListIndexRoute =
  ProtectedLayoutTransactionsLayoutTransactionsListIndexImport.update({
    id: '/transactions/list/',
    path: '/transactions/list/',
    getParentRoute: () => ProtectedLayoutTransactionsLayoutRoute,
  } as any)

const ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexRoute =
  ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexImport.update(
    {
      id: '/transactions/spendings/payees/',
      path: '/transactions/spendings/payees/',
      getParentRoute: () => ProtectedLayoutTransactionsLayoutRoute,
    } as any,
  )

const ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexRoute =
  ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexImport.update(
    {
      id: '/transactions/spendings/categories/',
      path: '/transactions/spendings/categories/',
      getParentRoute: () => ProtectedLayoutTransactionsLayoutRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protectedLayout': {
      id: '/_protectedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protectedLayout/_transactionsLayout': {
      id: '/_protectedLayout/_transactionsLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutTransactionsLayoutImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protectedLayout/': {
      id: '/_protectedLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protectedLayout/accounts/': {
      id: '/_protectedLayout/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedLayoutAccountsIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protectedLayout/payees/': {
      id: '/_protectedLayout/payees/'
      path: '/payees'
      fullPath: '/payees'
      preLoaderRoute: typeof ProtectedLayoutPayeesIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_publicLayout/login/': {
      id: '/_publicLayout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutLoginIndexImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_protectedLayout/_transactionsLayout/transactions/list/': {
      id: '/_protectedLayout/_transactionsLayout/transactions/list/'
      path: '/transactions/list'
      fullPath: '/transactions/list'
      preLoaderRoute: typeof ProtectedLayoutTransactionsLayoutTransactionsListIndexImport
      parentRoute: typeof ProtectedLayoutTransactionsLayoutImport
    }
    '/_protectedLayout/_transactionsLayout/transactions/spendings/categories/': {
      id: '/_protectedLayout/_transactionsLayout/transactions/spendings/categories/'
      path: '/transactions/spendings/categories'
      fullPath: '/transactions/spendings/categories'
      preLoaderRoute: typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexImport
      parentRoute: typeof ProtectedLayoutTransactionsLayoutImport
    }
    '/_protectedLayout/_transactionsLayout/transactions/spendings/payees/': {
      id: '/_protectedLayout/_transactionsLayout/transactions/spendings/payees/'
      path: '/transactions/spendings/payees'
      fullPath: '/transactions/spendings/payees'
      preLoaderRoute: typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexImport
      parentRoute: typeof ProtectedLayoutTransactionsLayoutImport
    }
  }
}

// Create and export the route tree

interface ProtectedLayoutTransactionsLayoutRouteChildren {
  ProtectedLayoutTransactionsLayoutTransactionsListIndexRoute: typeof ProtectedLayoutTransactionsLayoutTransactionsListIndexRoute
  ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexRoute: typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexRoute
  ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexRoute: typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexRoute
}

const ProtectedLayoutTransactionsLayoutRouteChildren: ProtectedLayoutTransactionsLayoutRouteChildren =
  {
    ProtectedLayoutTransactionsLayoutTransactionsListIndexRoute:
      ProtectedLayoutTransactionsLayoutTransactionsListIndexRoute,
    ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexRoute:
      ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexRoute,
    ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexRoute:
      ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexRoute,
  }

const ProtectedLayoutTransactionsLayoutRouteWithChildren =
  ProtectedLayoutTransactionsLayoutRoute._addFileChildren(
    ProtectedLayoutTransactionsLayoutRouteChildren,
  )

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutTransactionsLayoutRoute: typeof ProtectedLayoutTransactionsLayoutRouteWithChildren
  ProtectedLayoutIndexRoute: typeof ProtectedLayoutIndexRoute
  ProtectedLayoutAccountsIndexRoute: typeof ProtectedLayoutAccountsIndexRoute
  ProtectedLayoutPayeesIndexRoute: typeof ProtectedLayoutPayeesIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutTransactionsLayoutRoute:
    ProtectedLayoutTransactionsLayoutRouteWithChildren,
  ProtectedLayoutIndexRoute: ProtectedLayoutIndexRoute,
  ProtectedLayoutAccountsIndexRoute: ProtectedLayoutAccountsIndexRoute,
  ProtectedLayoutPayeesIndexRoute: ProtectedLayoutPayeesIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutLoginIndexRoute: typeof PublicLayoutLoginIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutLoginIndexRoute: PublicLayoutLoginIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedLayoutTransactionsLayoutRouteWithChildren
  '/': typeof ProtectedLayoutIndexRoute
  '/accounts': typeof ProtectedLayoutAccountsIndexRoute
  '/payees': typeof ProtectedLayoutPayeesIndexRoute
  '/login': typeof PublicLayoutLoginIndexRoute
  '/transactions/list': typeof ProtectedLayoutTransactionsLayoutTransactionsListIndexRoute
  '/transactions/spendings/categories': typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexRoute
  '/transactions/spendings/payees': typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexRoute
}

export interface FileRoutesByTo {
  '': typeof ProtectedLayoutTransactionsLayoutRouteWithChildren
  '/': typeof ProtectedLayoutIndexRoute
  '/accounts': typeof ProtectedLayoutAccountsIndexRoute
  '/payees': typeof ProtectedLayoutPayeesIndexRoute
  '/login': typeof PublicLayoutLoginIndexRoute
  '/transactions/list': typeof ProtectedLayoutTransactionsLayoutTransactionsListIndexRoute
  '/transactions/spendings/categories': typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexRoute
  '/transactions/spendings/payees': typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protectedLayout': typeof ProtectedLayoutRouteWithChildren
  '/_publicLayout': typeof PublicLayoutRouteWithChildren
  '/_protectedLayout/_transactionsLayout': typeof ProtectedLayoutTransactionsLayoutRouteWithChildren
  '/_protectedLayout/': typeof ProtectedLayoutIndexRoute
  '/_protectedLayout/accounts/': typeof ProtectedLayoutAccountsIndexRoute
  '/_protectedLayout/payees/': typeof ProtectedLayoutPayeesIndexRoute
  '/_publicLayout/login/': typeof PublicLayoutLoginIndexRoute
  '/_protectedLayout/_transactionsLayout/transactions/list/': typeof ProtectedLayoutTransactionsLayoutTransactionsListIndexRoute
  '/_protectedLayout/_transactionsLayout/transactions/spendings/categories/': typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsCategoriesIndexRoute
  '/_protectedLayout/_transactionsLayout/transactions/spendings/payees/': typeof ProtectedLayoutTransactionsLayoutTransactionsSpendingsPayeesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/accounts'
    | '/payees'
    | '/login'
    | '/transactions/list'
    | '/transactions/spendings/categories'
    | '/transactions/spendings/payees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/accounts'
    | '/payees'
    | '/login'
    | '/transactions/list'
    | '/transactions/spendings/categories'
    | '/transactions/spendings/payees'
  id:
    | '__root__'
    | '/_protectedLayout'
    | '/_publicLayout'
    | '/_protectedLayout/_transactionsLayout'
    | '/_protectedLayout/'
    | '/_protectedLayout/accounts/'
    | '/_protectedLayout/payees/'
    | '/_publicLayout/login/'
    | '/_protectedLayout/_transactionsLayout/transactions/list/'
    | '/_protectedLayout/_transactionsLayout/transactions/spendings/categories/'
    | '/_protectedLayout/_transactionsLayout/transactions/spendings/payees/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protectedLayout",
        "/_publicLayout"
      ]
    },
    "/_protectedLayout": {
      "filePath": "_protectedLayout.tsx",
      "children": [
        "/_protectedLayout/_transactionsLayout",
        "/_protectedLayout/",
        "/_protectedLayout/accounts/",
        "/_protectedLayout/payees/"
      ]
    },
    "/_publicLayout": {
      "filePath": "_publicLayout.tsx",
      "children": [
        "/_publicLayout/login/"
      ]
    },
    "/_protectedLayout/_transactionsLayout": {
      "filePath": "_protectedLayout/_transactionsLayout.tsx",
      "parent": "/_protectedLayout",
      "children": [
        "/_protectedLayout/_transactionsLayout/transactions/list/",
        "/_protectedLayout/_transactionsLayout/transactions/spendings/categories/",
        "/_protectedLayout/_transactionsLayout/transactions/spendings/payees/"
      ]
    },
    "/_protectedLayout/": {
      "filePath": "_protectedLayout/index.tsx",
      "parent": "/_protectedLayout"
    },
    "/_protectedLayout/accounts/": {
      "filePath": "_protectedLayout/accounts/index.tsx",
      "parent": "/_protectedLayout"
    },
    "/_protectedLayout/payees/": {
      "filePath": "_protectedLayout/payees/index.tsx",
      "parent": "/_protectedLayout"
    },
    "/_publicLayout/login/": {
      "filePath": "_publicLayout/login/index.tsx",
      "parent": "/_publicLayout"
    },
    "/_protectedLayout/_transactionsLayout/transactions/list/": {
      "filePath": "_protectedLayout/_transactionsLayout/transactions/list/index.tsx",
      "parent": "/_protectedLayout/_transactionsLayout"
    },
    "/_protectedLayout/_transactionsLayout/transactions/spendings/categories/": {
      "filePath": "_protectedLayout/_transactionsLayout/transactions/spendings/categories/index.tsx",
      "parent": "/_protectedLayout/_transactionsLayout"
    },
    "/_protectedLayout/_transactionsLayout/transactions/spendings/payees/": {
      "filePath": "_protectedLayout/_transactionsLayout/transactions/spendings/payees/index.tsx",
      "parent": "/_protectedLayout/_transactionsLayout"
    }
  }
}
ROUTE_MANIFEST_END */
