/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicLayoutImport } from './routes/_publicLayout'
import { Route as ProtectedLayoutImport } from './routes/_protectedLayout'
import { Route as ProtectedLayoutIndexImport } from './routes/_protectedLayout/index'
import { Route as PublicLayoutLoginIndexImport } from './routes/_publicLayout/login/index'
import { Route as ProtectedLayoutTransactionsIndexImport } from './routes/_protectedLayout/transactions/index'
import { Route as ProtectedLayoutSpendingsIndexImport } from './routes/_protectedLayout/spendings/index'
import { Route as ProtectedLayoutPayeesIndexImport } from './routes/_protectedLayout/payees/index'

// Create/Update Routes

const PublicLayoutRoute = PublicLayoutImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_protectedLayout',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutIndexRoute = ProtectedLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const PublicLayoutLoginIndexRoute = PublicLayoutLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const ProtectedLayoutTransactionsIndexRoute =
  ProtectedLayoutTransactionsIndexImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedLayoutSpendingsIndexRoute =
  ProtectedLayoutSpendingsIndexImport.update({
    id: '/spendings/',
    path: '/spendings/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedLayoutPayeesIndexRoute = ProtectedLayoutPayeesIndexImport.update(
  {
    id: '/payees/',
    path: '/payees/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protectedLayout': {
      id: '/_protectedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protectedLayout/': {
      id: '/_protectedLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protectedLayout/payees/': {
      id: '/_protectedLayout/payees/'
      path: '/payees'
      fullPath: '/payees'
      preLoaderRoute: typeof ProtectedLayoutPayeesIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protectedLayout/spendings/': {
      id: '/_protectedLayout/spendings/'
      path: '/spendings'
      fullPath: '/spendings'
      preLoaderRoute: typeof ProtectedLayoutSpendingsIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protectedLayout/transactions/': {
      id: '/_protectedLayout/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ProtectedLayoutTransactionsIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_publicLayout/login/': {
      id: '/_publicLayout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutLoginIndexImport
      parentRoute: typeof PublicLayoutImport
    }
  }
}

// Create and export the route tree

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutIndexRoute: typeof ProtectedLayoutIndexRoute
  ProtectedLayoutPayeesIndexRoute: typeof ProtectedLayoutPayeesIndexRoute
  ProtectedLayoutSpendingsIndexRoute: typeof ProtectedLayoutSpendingsIndexRoute
  ProtectedLayoutTransactionsIndexRoute: typeof ProtectedLayoutTransactionsIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutIndexRoute: ProtectedLayoutIndexRoute,
  ProtectedLayoutPayeesIndexRoute: ProtectedLayoutPayeesIndexRoute,
  ProtectedLayoutSpendingsIndexRoute: ProtectedLayoutSpendingsIndexRoute,
  ProtectedLayoutTransactionsIndexRoute: ProtectedLayoutTransactionsIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutLoginIndexRoute: typeof PublicLayoutLoginIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutLoginIndexRoute: PublicLayoutLoginIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PublicLayoutRouteWithChildren
  '/': typeof ProtectedLayoutIndexRoute
  '/payees': typeof ProtectedLayoutPayeesIndexRoute
  '/spendings': typeof ProtectedLayoutSpendingsIndexRoute
  '/transactions': typeof ProtectedLayoutTransactionsIndexRoute
  '/login': typeof PublicLayoutLoginIndexRoute
}

export interface FileRoutesByTo {
  '': typeof PublicLayoutRouteWithChildren
  '/': typeof ProtectedLayoutIndexRoute
  '/payees': typeof ProtectedLayoutPayeesIndexRoute
  '/spendings': typeof ProtectedLayoutSpendingsIndexRoute
  '/transactions': typeof ProtectedLayoutTransactionsIndexRoute
  '/login': typeof PublicLayoutLoginIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protectedLayout': typeof ProtectedLayoutRouteWithChildren
  '/_publicLayout': typeof PublicLayoutRouteWithChildren
  '/_protectedLayout/': typeof ProtectedLayoutIndexRoute
  '/_protectedLayout/payees/': typeof ProtectedLayoutPayeesIndexRoute
  '/_protectedLayout/spendings/': typeof ProtectedLayoutSpendingsIndexRoute
  '/_protectedLayout/transactions/': typeof ProtectedLayoutTransactionsIndexRoute
  '/_publicLayout/login/': typeof PublicLayoutLoginIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/payees' | '/spendings' | '/transactions' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/' | '/payees' | '/spendings' | '/transactions' | '/login'
  id:
    | '__root__'
    | '/_protectedLayout'
    | '/_publicLayout'
    | '/_protectedLayout/'
    | '/_protectedLayout/payees/'
    | '/_protectedLayout/spendings/'
    | '/_protectedLayout/transactions/'
    | '/_publicLayout/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protectedLayout",
        "/_publicLayout"
      ]
    },
    "/_protectedLayout": {
      "filePath": "_protectedLayout.tsx",
      "children": [
        "/_protectedLayout/",
        "/_protectedLayout/payees/",
        "/_protectedLayout/spendings/",
        "/_protectedLayout/transactions/"
      ]
    },
    "/_publicLayout": {
      "filePath": "_publicLayout.tsx",
      "children": [
        "/_publicLayout/login/"
      ]
    },
    "/_protectedLayout/": {
      "filePath": "_protectedLayout/index.tsx",
      "parent": "/_protectedLayout"
    },
    "/_protectedLayout/payees/": {
      "filePath": "_protectedLayout/payees/index.tsx",
      "parent": "/_protectedLayout"
    },
    "/_protectedLayout/spendings/": {
      "filePath": "_protectedLayout/spendings/index.tsx",
      "parent": "/_protectedLayout"
    },
    "/_protectedLayout/transactions/": {
      "filePath": "_protectedLayout/transactions/index.tsx",
      "parent": "/_protectedLayout"
    },
    "/_publicLayout/login/": {
      "filePath": "_publicLayout/login/index.tsx",
      "parent": "/_publicLayout"
    }
  }
}
ROUTE_MANIFEST_END */
